### ISSUE TITLE
api for ios, for few shabat in advence

### ISSUE THREAD

**Issue by AlTidag** [hebcal/hebcal-es6#226] opened 2022-09-21 19:01 UTC
hello.
i have searched for option to get data for few Shabbat in advance by entering dates "from" - "till".
but its not working.
on the week days it works with choosing dates though.
why ?

**Comment by mjradwin** [comment] 2022-09-21 19:48
Hi, thanks for your question. (This appears to be a duplicate of the post "[shabbat API info by start= and end= in zmanim api not exist](https://hebcal.userecho.com/en/communities/1/topics/1103-shabbat-api-info-by-start-and-end-in-zmanim-api-not-exist)" on our UserEcho support page)

The behavior of the [Shabbat Times rest API](https://www.hebcal.com/home/197/shabbat-times-rest-api) is by design. The Shabbat API always displays the current week's information, including both Friday and Saturday, even if Friday has already passed. No, there is no way to change this behavior by specifying different start/end parameters.

If you want control over date ranges please instead use our [Jewish calendar API](https://www.hebcal.com/home/195/jewish-calendar-rest-api) and specify start and end parameters. The returned JSON is nearly identical to the Shabbat API so it should be easy to transition to this supported API.

**Closed by mjradwin** 2022-09-21 19:48 UTC
